import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,applyCommand} from '../panel/domain.mjs';
import {statisticsData,statisticsRange,statisticsResults} from '../panel/statistics.mjs';
function fixture(){const s=emptyState();const put=r=>s.records[r.id]=r;put({id:'a',kind:'clients',name:'A',source:'Referido',ageRange:'25–34',gender:'Mujer'});put({id:'b',kind:'clients',name:'B',instagram:'cuenta'});const sale=(id,date,clientId,price,status='pendiente')=>put({id,kind:'invoices',number:id,date,clientId,status,lines:[{description:'Trabajo a medida',quantity:1,price}]});sale('old','2026-08-10','a',100);sale('one','2026-09-05','a',200);sale('two','2026-09-06','b',300);sale('three','2026-09-07','b',100);sale('draft','2026-09-01','b',500,'borrador');sale('void','2026-09-01','b',500,'anulada');put({id:'quote',kind:'quotes',status:'aprobada',date:'2026-09-01',lines:[{description:'Trabajo',quantity:1,price:900}]});put({id:'payment',kind:'payments',target:'old',date:'2026-09-01',amount:10000});put({id:'order',kind:'orders',status:'entregado',due:'2026-08-01',deliveredAt:'2026-09-02T14:00:00Z'});return s;}
test('ventas por fecha, sin borradores, anuladas, cotizaciones ni cobros duplicados',()=>{const d=statisticsData(fixture(),'2026-09','2026-09','2026-09-30');assert.equal(d.revenue,60000);assert.equal(d.sales.length,3);assert.equal(d.average,20000);assert.equal(d.orders.length,1);assert.equal(d.buyers.length,2);assert.equal(d.newBuyers.length,1);assert.equal(d.recurrentBuyers.length,1);assert.equal(d.months[0].amount,60000);});
test('origen y perfil solo explícitos, con desconocidos incluidos',()=>{const d=statisticsData(fixture(),'2026-09','2026-09','2026-09-30');assert.equal(d.origins.find(g=>g.label==='Sin especificar').clients.length,1);assert.ok(!d.origins.some(g=>g.label==='Instagram'));assert.equal(d.ages.find(g=>g.label==='25–34').clients[0].id,'a');assert.equal(d.genders.find(g=>g.label==='Sin especificar').clients[0].id,'b');});
test('renglones fuera de catálogo, cantidades e importes tras descuento rastreables',()=>{const s=fixture();s.records.two.lines=[{description:'Otro servicio',quantity:3,price:100}];s.records.two.discount=30;const d=statisticsData(s,'2026-09','2026-09','2026-09-30');assert.equal(d.products.find(p=>p.name==='Otro servicio').quantity,3);assert.equal(d.products.find(p=>p.name==='Otro servicio').amount,27000);assert.equal(d.products.find(p=>p.name==='Otro servicio').sales[0].id,'two');assert.equal(d.products.find(p=>p.name==='Trabajo a medida').quantity,2);assert.ok(statisticsResults(d,'amount').indexOf('Trabajo a medida')<statisticsResults(d,'amount').indexOf('Otro servicio'));assert.ok(statisticsResults(d,'quantity').indexOf('Otro servicio')<statisticsResults(d,'quantity').indexOf('Trabajo a medida'));});
test('períodos equivalentes por días, comparación válida y promedio vacío',()=>{const r=statisticsRange('2026-09','2026-09','2026-09-15');assert.equal(r.days,15);assert.equal(r.previousStart,'2026-08-17');assert.equal(r.previousEnd,'2026-08-31');const d=statisticsData(fixture(),'2026-09','2026-09','2026-09-30');assert.equal(d.comparison,500);const blank=statisticsData(emptyState(),'2026-09','2026-09','2026-09-30');assert.equal(blank.average,null);assert.equal(blank.comparison,null);assert.match(statisticsResults(blank),/Sin datos/);assert.throws(()=>statisticsRange('2026-10','2026-09'),/mes inicial/);});
test('fecha de entrega local y documentos archivados conservan el historial',()=>{const s=fixture();s.records.one.archived=true;s.records.order.deliveredAt='2026-09-01T02:00:00Z';const d=statisticsData(s,'2026-09','2026-09','2026-09-30');assert.equal(d.revenue,60000);assert.equal(d.orders.length,0);});
test('guardar nuevamente un pedido entregado no cambia su período de entrega',()=>{const s=fixture();const updated=applyCommand(s,{action:'status',id:'order',status:'entregado'},{at:'2026-10-01T14:00:00Z'}).state;assert.equal(updated.records.order.deliveredAt,s.records.order.deliveredAt);assert.equal(statisticsData(updated,'2026-09','2026-09','2026-09-30').orders.length,1);});
