import test from 'node:test';import assert from 'node:assert/strict';
import {emptyState,applyCommand,calculate,totals,balance,paid,stock,nextDate,nextCommitment,cashflow,get,list} from '../panel/domain.mjs';
import {documentPdf} from '../panel/pdf.mjs';
function setup(){let s=emptyState(),i=0;const run=cmd=>{const out=applyCommand(s,cmd,{id:`id-${++i}`,at:'2026-09-07T12:00:00Z'});s=out.state;return out.result;};const client=run({action:'save',kind:'clients',data:{name:'Prueba'}});return {run,client,get state(){return s;}};}
const quoteData=client=>({name:'Encargo',clientId:client,date:'2026-09-07',lines:[{description:'Pieza',quantity:2,price:100}],discount:0,shipping:0});
test('margen sobre venta, comisión y mano de obra no se confunden con recargo',()=>{const c=calculate({units:2,hours:1,hourly:100,materials:[{quantity:2,unitCost:50}],mode:'margin',margin:40,feePercent:10});assert.equal(c.cost,20000);assert.equal(c.sale,40000);assert.equal(c.profit,16000);assert.equal(c.margin,40);assert.equal(c.markup,80);assert.throws(()=>calculate({margin:90,feePercent:10}),/menores/);});
test('descuento, envío, impuesto y anticipo con validación',()=>{const t=totals({lines:[{quantity:2,price:100}],discountType:'percent',discount:10,shipping:20,taxPercent:10,advanceType:'percent',advance:50});assert.equal(t.total,21800);assert.equal(t.advance,10900);assert.throws(()=>totals({lines:[{quantity:1,price:2}],discount:3}),/supera/);});
test('cotización → pedido y factura → pagos y reembolso sin duplicar ingresos',()=>{const x=setup(),q=x.run({action:'save',kind:'quotes',data:quoteData(x.client)});x.run({action:'issue',id:q});x.run({action:'approve',id:q});const o=x.run({action:'convert',id:q,kind:'orders'}),f=x.run({action:'convert',id:q,kind:'invoices'});assert.equal(get(x.state,o).number,'PED-0001');assert.equal(get(x.state,f).number,'FAC-0001');assert.throws(()=>x.run({action:'convert',id:q,kind:'invoices'}),/Ya existe/);x.run({action:'issue',id:f});const p=x.run({action:'payment',target:f,amount:50});assert.equal(balance(x.state,get(x.state,f)),15000);assert.throws(()=>x.run({action:'payment',target:f,amount:151}),/supera/);x.run({action:'payment',target:f,type:'refund',originalId:p,amount:20,reason:'Ajuste'});assert.equal(paid(x.state,f),3000);assert.equal(cashflow(x.state).income-cashflow(x.state).expense,3000);assert.throws(()=>x.run({action:'payment',target:f,type:'refund',originalId:p,amount:31,reason:'Ajuste'}),/supera/);});
test('documentos enviados inmutables y nuevas versiones conservadas',()=>{const x=setup(),q=x.run({action:'save',kind:'quotes',data:quoteData(x.client)});x.run({action:'issue',id:q});assert.throws(()=>x.run({action:'save',kind:'quotes',id:q,data:{name:'Cambio'}}),/versión/);const v=x.run({action:'revise',id:q});assert.equal(get(x.state,v).revision,2);assert.equal(get(x.state,q).revision||1,1);assert.equal(get(x.state,v).number,get(x.state,q).number);});
test('compra actualiza existencias una vez y sus pagos aparecen en finanzas',()=>{const x=setup(),m=x.run({action:'save',kind:'materials',data:{name:'Papel',packageUnits:20,packageCost:100,track:true}}),p=x.run({action:'save',kind:'purchases',data:{name:'Compra papel',materialId:m,quantity:20,total:100}});x.run({action:'purchase',id:p});assert.equal(stock(x.state,m),20);assert.throws(()=>x.run({action:'purchase',id:p}),/ya fue/);x.run({action:'payment',target:p,amount:50});assert.equal(cashflow(x.state).expense,5000);assert.equal(cashflow(x.state).payable,5000);});
test('consumo agrupa materiales, evita stock negativo y rechaza segunda confirmación',()=>{const x=setup(),m=x.run({action:'save',kind:'materials',data:{name:'Papel',packageUnits:1,packageCost:10,track:true}});x.run({action:'adjustStock',materialId:m,quantity:5,reason:'Inicial'});const o=x.run({action:'save',kind:'orders',data:quoteData(x.client)});assert.throws(()=>x.run({action:'consume',id:o,lines:[{materialId:m,quantity:3},{materialId:m,quantity:3}]}),/suficientes/);assert.equal(stock(x.state,m),5);x.run({action:'consume',id:o,lines:[{materialId:m,quantity:2}]});assert.equal(stock(x.state,m),3);assert.throws(()=>x.run({action:'consume',id:o,lines:[{materialId:m,quantity:1}]}),/ya se confirmó/);});
test('tarea mensual respeta fin de mes y no duplica al completar dos veces',()=>{assert.equal(nextDate('2026-01-31','mensual'),'2026-02-28');const x=setup(),t=x.run({action:'save',kind:'tasks',data:{name:'Revisar',date:'2026-01-31',repeat:'mensual',status:'pendiente'}});x.run({action:'status',id:t,status:'completada'});x.run({action:'status',id:t,status:'completada'});assert.equal(list(x.state,'tasks').length,2);});
test('próximo compromiso prioriza fechas abiertas e ignora registros cerrados',()=>{const s=emptyState();s.records={done:{id:'done',kind:'tasks',name:'Terminada',date:'2026-09-01',status:'completada'},quote:{id:'quote',kind:'quotes',name:'Propuesta',number:'COT-0001',validUntil:'2026-09-11',status:'enviada'},order:{id:'order',kind:'orders',name:'Letrero',number:'PED-0001',due:'2026-09-13',status:'en producción'}};assert.equal(nextCommitment(s,'2026-09-12').id,'quote');s.records.quote.status='aprobada';assert.equal(nextCommitment(s,'2026-09-12').id,'order');s.records.order.status='entregado';assert.equal(nextCommitment(s,'2026-09-12'),null);});
test('PDF descargable no incluye costos internos y pagina documentos largos',async()=>{const q={...quoteData('x'),kind:'invoices',number:'FAC-0001',status:'pendiente',issuer:{name:'Life Deco Art'},client:{name:'Prueba'},actualCost:99999,lines:Array.from({length:80},(_,i)=>({description:`Artículo ${i}`,quantity:1,price:100}))};const pdf=await documentPdf(q).text();assert.ok(pdf.startsWith('%PDF-1.4'));assert.ok(pdf.includes('FACTURA SIN COMPROBANTE FISCAL'));assert.ok(!pdf.includes('99999'));assert.ok((pdf.match(/\/Type \/Page /g)||[]).length>1);});
