import {emptyState,list,get,money,cents,calculate,totals,paid,balance,documentStatus,stock,events,today,cashflow} from './domain.mjs';
import {schemas,settingsFields} from './schema.mjs';
import {documentPdf} from './pdf.mjs';

const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=url=>{try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}};
const icon=(name='box')=>`<svg viewBox="0 0 24 24" aria-hidden="true">${({home:'<path d="M3 10 12 3l9 7v11h-6v-7H9v7H3V10Z"/>',people:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-4a6 6 0 0 1 12 0v4M17 4a3 3 0 0 1 0 6m1 4a5 5 0 0 1 3 5v2"/>',doc:'<path d="M5 2h10l4 4v16H5ZM14 2v5h5M8 12h8M8 16h8"/>',box:'<path d="m3 7 9-4 9 4v11l-9 4-9-4Zm0 0 9 5 9-5M12 12v10"/>',catalog:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',calendar:'<rect x="3" y="5" width="18" height="17" rx="2"/><path d="M7 2v6m10-6v6M3 11h18M7 15h3m4 0h3m-10 4h3"/>',money:'<rect x="2" y="5" width="20" height="14" rx="2"/><circle cx="12" cy="12" r="3"/><path d="M5 9v6m14-6v6"/>',image:'<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8" cy="8" r="2"/><path d="m3 18 6-6 4 4 3-5 5 7"/>',key:'<circle cx="8" cy="9" r="5"/><path d="m12 13 8 8m-5-5 3-3m0 6 3-3"/>',settings:'<path d="M4 6h16M4 12h16M4 18h16M8 4v4m8 2v4m-6 2v4"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',plus:'<path d="M12 4v16M4 12h16"/>'})[name]||''}</svg>`;
const nav=[
 ['home','Inicio','home',['home']],
 ['clients','Clientes','people',['clients']],
 ['quotes','Ventas','doc',['quotes','invoices']],
 ['orders','Pendientes','box',['orders']],
 ['products','Catálogo','catalog',['products','calculations','materials','purchases']],
 ['finance','Finanzas','money',['finance','expenses']],
 ['content','Contenido','image',['content','campaigns','resources']],
 ['tasks','Agenda','calendar',['tasks']],
 ['accounts','Administración','settings',['accounts','settings']]
];
let store,state=emptyState(),user=null,busy=false,route='home',recordId='',mode='',search='',filter='',calendarMode='month',calendarDate=today(),listMode='list',objectUrls=[],pageTitle='',pageDescription='',pageActions='';
function notice(text,error=false){const n=$('#notice');n.textContent=text;n.className='show';n.setAttribute('role',error?'alert':'status');clearTimeout(notice.timer);notice.timer=setTimeout(()=>n.className='',6500);}
function ask(message,withReason=false){return new Promise(resolve=>{const previous=document.activeElement,dialog=document.createElement('dialog');dialog.className='confirm-dialog';dialog.innerHTML=`<h2>Confirmar cambio</h2><p>${esc(message)}</p>${withReason?'<label class="field"><span>Motivo</span><textarea id="confirmation-reason" required></textarea></label>':''}<div class="actions section-space"><button type="button" data-confirm="cancel">Cancelar</button><button type="button" class="primary" data-confirm="ok">Confirmar</button></div>`;const finish=value=>{dialog.close();dialog.remove();previous?.focus();resolve(value);};dialog.addEventListener('cancel',e=>{e.preventDefault();finish(null);});dialog.addEventListener('click',e=>{const choice=e.target.dataset.confirm;if(choice==='cancel')finish(null);if(choice==='ok'){const reason=dialog.querySelector('textarea');if(reason&&!reason.value.trim()){reason.reportValidity();reason.focus();return;}finish(withReason?reason.value.trim():true);}});document.body.append(dialog);dialog.showModal();dialog.querySelector(withReason?'textarea':'button').focus();});}
function errorMessage(e){if(e?.code?.startsWith('auth/'))return 'No pudimos iniciar sesión. Revisa el correo y la contraseña, o recupera tu acceso.';if(e?.code==='permission-denied'||e?.code==='storage/unauthorized'||e?.message==='PANEL_ACCESS_PENDING')return 'El acceso privado del panel todavía necesita habilitación en Firebase. Tus datos no se guardarán en espacios públicos.';return e?.message||'No se pudo completar la acción. Vuelve a intentarlo.';}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
const btn=(label,action,attrs='',primary=false)=>`<button type="button" data-action="${action}" ${attrs} class="${primary?'primary':''}">${label}</button>`;
function displayField(f,value){if(f.type!=='select')return value;const option=f.options.find(o=>Array.isArray(o)?o[0]===value:o===value);return Array.isArray(option)?option[1]:value;}
const link=(kind,r)=>kind==='movements'?esc(r.name):`<a href="#${kind}/${r.id}">${esc(r.number||r.name)}</a>`;
const badge=status=>`<span class="badge ${['pagada','aprobada','entregado','completada'].includes(status)?'good':['vencida','pendiente','alta'].includes(status)?'warn':''}">${esc(status)}</span>`;
function loginScreen(message=''){$('#app').innerHTML=`<main id="main" class="login"><section class="login-card"><h1 class="brand-script">Life Deco Art</h1><h2>Tu espacio de trabajo</h2><p class="muted">Entra con tu cuenta privada del hub.</p><form id="login-form"><label>Correo<input type="email" name="email" autocomplete="username" required></label><label>Contraseña<input type="password" name="password" autocomplete="current-password" required></label><button class="primary" type="submit">Entrar al panel</button>${btn('Recuperar acceso','reset')}</form><div id="login-error" ${message?'class="error" role="alert"':''}>${esc(message)}</div><p class="sensitive-note section-space">Solo tú tienes acceso a la información de tu negocio.</p></section></main>`;}
function parseRoute(){const parts=location.hash.slice(1).split('/');route=parts[0]||'home';recordId=parts[1]||'';mode=parts[2]||'';if(recordId==='new'){recordId='';mode='edit';}search='';filter='';}
function quickNotes(){return Object.values(state.records).filter(r=>r.kind==='resources'&&r.recordType==='quick-note'&&!r.archived).sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')));}
function noteTime(value){if(!value)return '';const date=new Date(value);return Number.isNaN(+date)?'':new Intl.DateTimeFormat('es-DO',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Santo_Domingo'}).format(date);}
function quickNotesDialog(){const notes=quickNotes();return `<dialog class="quick-notes-dialog" id="quick-notes-dialog"><div class="quick-notes-head"><div><h2>Notas rápidas</h2><p>Ideas, apuntes de reuniones y recordatorios breves.</p></div><button type="button" data-action="notes-close" aria-label="Cerrar notas rápidas">×</button></div><form id="quick-note-form"><div class="field"><textarea id="quick-note-text" name="note" rows="4" aria-label="Nueva nota" placeholder="Escribe aquí lo que no quieres olvidar…" required></textarea></div><div class="quick-note-actions"><button class="primary" type="submit">Guardar</button></div></form><section class="quick-notes-list" aria-label="Notas guardadas"><h3>Recientes</h3>${notes.length?notes.map(note=>`<article><div><p>${esc(note.note)}</p><time datetime="${esc(note.createdAt||'')}">${esc(noteTime(note.createdAt))}</time></div><button type="button" class="quick-note-delete" data-action="delete-note" data-id="${esc(note.id)}">Eliminar</button></article>`).join(''):'<p class="muted">Todavía no has guardado notas.</p>'}</section></dialog>`;}
function notesButton(){return `<button type="button" class="primary quick-notes-trigger" data-action="notes">${icon('doc')}<span>Notas rápidas</span></button>`;}
function shell(content){const active=nav.find(([, , ,routes])=>routes.includes(route))?.[0]||'home';$('#app').innerHTML=`<div class="shell"><aside class="sidebar" id="sidebar"><button type="button" class="mobile-close" data-action="menu-close">Cerrar menú</button><a class="brand" href="#home"><span class="brand-name">LIFE DECO ART</span><span class="brand-context">HUB — Gestión</span></a><nav aria-label="Menú principal">${nav.map(([key,label,i])=>`<a href="#${key}" ${active===key?'aria-current="page"':''}>${icon(i)}<span>${label}</span></a>`).join('')}</nav><div class="sidebar-footer"><button type="button" data-action="logout">Cerrar sesión</button></div></aside><div class="workspace"><header class="topbar"><button class="menu-toggle" data-action="menu" aria-label="Abrir menú" aria-controls="sidebar" aria-expanded="false">${icon('menu')}</button><div class="topbar-copy"><h1>${esc(pageTitle)}</h1><p>${esc(pageDescription)}</p></div><div class="actions">${pageActions}</div></header><main id="main" class="main" tabindex="-1">${content}</main></div></div>${route==='home'?quickNotesDialog():''}`;hydrateImages();}
const head=(title,description='',actions='')=>{pageTitle=title;pageDescription=description||schemas[route]?.description||'Tu espacio de trabajo.';pageActions=actions;return '';};
function empty(kind){return `<div class="empty">${icon(kind==='clients'?'people':'doc')}<h2>Todavía no hay ${esc(schemas[kind]?.title.toLowerCase()||'registros')}</h2><p>Empieza con tu primer registro. Aquí podrás encontrarlo y darle seguimiento.</p>${btn('Crear '+schemas[kind].singular,'new',`data-kind="${kind}"`,true)}</div>`;}
function tabs(){let items=[];if(['quotes','invoices'].includes(route))items=[['quotes','Cotizaciones'],['invoices','Facturas']];if(['products','calculations','materials','purchases'].includes(route))items=[['products','Productos y servicios'],['calculations','Calculadora'],['materials','Materiales e inventario'],['purchases','Compras']];if(['finance','expenses'].includes(route))items=[['finance','Movimientos y saldos'],['expenses','Gastos']];if(['content','campaigns','resources'].includes(route))items=[['content','Planificación'],['campaigns','Campañas'],['resources','Recursos de marca']];if(route==='tasks')items=[['tasks','Tareas'],['tasks/calendar','Calendario']];if(['accounts','settings'].includes(route))items=[['accounts','Accesos y cuentas'],['settings','Configuración']];if(!items.length)return '';return `<nav class="tabs" aria-label="Secciones relacionadas">${items.map(([key,label])=>{const [itemRoute,itemRecord='']=key.split('/'),selected=route===itemRoute&&(itemRecord?recordId===itemRecord:recordId!=='calendar');return `<a class="${selected?'active':''}" ${selected?'aria-current="page"':''} href="#${key}">${label}</a>`;}).join('')}</nav>`;}
function dataTable(kind,rows){return `<div class="table-wrap"><table><thead><tr><th>${['quotes','invoices','orders'].includes(kind)?'Documento':'Nombre'}</th><th>Detalle</th><th>Estado</th><th>Importe / fecha</th></tr></thead><tbody>${rows.map(r=>{
 let detail=r.category||r.email||r.channel||r.supplier||r.type||'',last=r.date||r.renewal||'';
 if(['quotes','invoices','orders'].includes(kind)){detail=state.records[r.clientId]?.name||r.client?.name||'';last=money(totals(r).total);}if(kind==='calculations'){const c=calculate(r);detail=`${c.units} unidades · ${c.margin.toFixed(1)} % margen`;last=money(c.sale);}if(kind==='materials'){detail=r.track?`${stock(state,r.id)} ${r.unit||'unidades'} disponibles`:'Sin control de existencias';last=money(cents(r.unitCost));}if(kind==='purchases')last=money(cents(r.total));if(kind==='expenses')last=money(cents(r.amount));if(kind==='products')last=r.pricing==='por cotizar'?'Por cotizar':money(cents(r.price));
 return `<tr><td>${link(kind,r)}${r.number?`<br><small>${esc(r.name)}${r.revision>1?' · v'+r.revision:''}</small>`:''}</td><td>${esc(detail)}</td><td>${badge(r.archived?'archivado':documentStatus(state,r))}</td><td class="num">${esc(last)}</td></tr>`;}).join('')}</tbody></table></div>`;}
function listPage(){const schema=schemas[route];if(!schema)return head('Página no encontrada')+'<a href="#home">Volver al inicio</a>';const rows=list(state,route,true).filter(r=>r.recordType!=='quick-note');return head(schema.title,schema.description,btn('Crear '+schema.singular,'new',`data-kind="${route}"`,true))+tabs()+`<div class="toolbar"><label class="sr-search"><input id="search" type="search" placeholder="Buscar en ${esc(schema.title.toLowerCase())}" aria-label="Buscar registros"></label><select id="filter" aria-label="Filtrar registros"><option value="">Activos</option><option value="all">Todos, incluidos archivados</option><option value="archived">Archivados</option>${[...new Set(rows.map(r=>documentStatus(state,r)))].sort().map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('')}</select>${['orders','content','tasks'].includes(route)?btn(listMode==='board'?'Ver lista':'Ver tablero','toggle-board'):''}${route==='tasks'?btn('Ver calendario','calendar'):''}${btn('Exportar CSV','csv')}</div><div id="list-results">${listResults()}</div>`;}
function filtered(){return list(state,route,true).filter(r=>r.recordType!=='quick-note').filter(r=>filter==='all'||(filter==='archived'?r.archived:!r.archived&&(!filter||documentStatus(state,r)===filter))).filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));}
function listResults(){const rows=filtered();if(!rows.length)return search||filter?'<div class="sheet empty"><p>No hay resultados con estos filtros.</p></div>':`<div class="sheet">${empty(route)}</div>`;if(route==='resources')return `<div class="resource-grid">${rows.map(r=>`<article class="resource-card"><div class="resource-image">${r.path&&r.mime?.startsWith('image/')?`<img data-resource="${r.id}" alt="${esc(r.name)}">`:icon('image')}</div><div class="resource-body">${link(route,r)}<p>${esc(r.category||r.role||'Recurso')}</p>${badge(r.visibility||'interno')}</div></article>`).join('')}</div>`;if(listMode==='board'&&['orders','content','tasks'].includes(route)){const states=route==='orders'?['pendiente','en diseño','esperando aprobación','en producción','listo para entregar','entregado','cancelado']:route==='content'?['idea','en preparación','listo','programado','publicado']:['pendiente','en curso','completada','cancelada'];return `<div class="board">${states.map(status=>`<section class="board-col"><h2>${esc(status)} · ${rows.filter(r=>r.status===status).length}</h2>${rows.filter(r=>r.status===status).map(r=>`<a class="board-item" href="#${route}/${r.id}">${esc(r.name)}<small>${esc(r.number||r.date||r.due||'')}</small></a>`).join('')}</section>`).join('')}</div>`;}return `<div class="sheet">${dataTable(route,rows)}</div>`;}
function agendaRows(rows){return rows.length?rows.map(r=>`<div class="agenda-row"><div>${link(r.kind,r)}<small>${esc(r.priority||schemas[r.kind]?.title||'')}</small></div><span class="num">${esc(r.eventDate||r.due||'Sin fecha')}</span></div>`).join(''):'<p class="muted">No hay fechas pendientes.</p>';}
function home(){const date=today(),flow=cashflow(state,date.slice(0,7)+'-01',date),quotes=list(state,'quotes').filter(r=>['enviada','vencida'].includes(documentStatus(state,r))),orders=list(state,'orders').filter(r=>!['entregado','cancelado'].includes(r.status)),low=list(state,'materials').filter(r=>r.track&&stock(state,r.id)<=Number(r.minimum||0));return head('Tu negocio, al día','Un lugar para organizar lo que viene.',notesButton())+`<div class="overview"><div><small>Por cobrar</small><strong>${money(flow.receivable)}</strong></div><div><small>Pedidos en proceso</small><strong>${orders.length}</strong></div><div><small>Cobros y entradas del mes</small><strong>${money(flow.income)}</strong></div><div><small>Pagos y salidas del mes</small><strong>${money(flow.expense)}</strong></div></div><div class="two-col"><section class="sheet sheet-pad"><h2>Agenda y próximas entregas</h2>${agendaRows(events(state).slice(0,8))}<a href="#tasks/calendar">Abrir calendario</a></section><section><div class="sheet sheet-pad"><h2>Cotizaciones por responder</h2>${quotes.length?quotes.slice(0,5).map(r=>`<div class="agenda-row"><div>${link('quotes',r)}<small>${esc(r.name)}</small></div>${badge(documentStatus(state,r))}</div>`).join(''):'<p class="muted">No hay propuestas pendientes de respuesta.</p>'}</div><div class="section-space sheet sheet-pad"><h2>Materiales por revisar</h2>${low.length?low.map(r=>`<div class="agenda-row">${link('materials',r)}<span>${stock(state,r.id)} ${esc(r.unit)}</span></div>`).join(''):'<p class="muted">No hay avisos de existencias bajas.</p>'}</div></section></div>`;}
function field(f,data={}){const value=data[f.key]??f.value??'',id='f-'+f.key+'-'+crypto.randomUUID();let control;if(f.type==='textarea')control=`<textarea id="${id}" name="${f.key}" rows="3">${esc(value)}</textarea>`;else if(f.type==='checkbox')control=`<input id="${id}" name="${f.key}" type="checkbox" ${value?'checked':''}>`;else if(['select','ref'].includes(f.type)){const options=f.type==='ref'?[['','Sin seleccionar'],...list(state,f.ref).filter(r=>r.recordType!=='quick-note').map(r=>[r.id,r.number?`${r.number} · ${r.name}`:r.name])]:f.options.map(o=>Array.isArray(o)?o:[o,o]);control=`<select id="${id}" name="${f.key}">${options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select>`;}else control=`<input id="${id}" name="${f.key}" type="${f.type}" ${f.type==='file'?'accept="image/png,image/jpeg,image/webp,image/gif,video/mp4,video/webm,application/pdf"':`value="${esc(value)}"`} ${f.type==='number'?`step="any" min="${f.min??0}"`:''} ${f.required?'required':''} ${f.type==='url'?'placeholder="https://…"':''}>`;return `<label class="field ${f.type==='textarea'?'wide':''}" for="${id}"><span>${esc(f.label)}${f.required?' *':''}</span>${control}</label>`;}
function lineRow(line={},materials=false){return `<div class="line-row ${materials?'material':''}">${materials?`<label>Material<select data-line="materialId"><option value="">Otro material</option>${list(state,'materials').map(m=>`<option value="${m.id}" ${m.id===line.materialId?'selected':''}>${esc(m.name)}</option>`).join('')}</select><input data-line="description" aria-label="Nombre del material" placeholder="Nombre del material" value="${esc(line.description||'')}"></label>`:`<label>Concepto<input data-line="description" value="${esc(line.description||'')}" required></label>`}<label>Cantidad<input data-line="quantity" type="number" min="0.001" step="any" value="${esc(line.quantity??1)}" required></label><label>${materials?'Costo unitario':'Precio unitario'} RD$<input data-line="${materials?'unitCost':'price'}" type="number" min="0" step="any" value="${esc(line.unitCost??line.price??0)}" required></label><button type="button" data-action="remove-line" aria-label="Quitar este concepto">×</button></div>`;}
function readForm(form,fields){const fd=new FormData(form),data={};for(const f of fields){if(f.type==='file')continue;data[f.key]=f.type==='checkbox'?fd.has(f.key):f.type==='number'?Number(fd.get(f.key)||0):String(fd.get(f.key)||'').trim();if(f.type==='url'&&data[f.key]&&!safeUrl(data[f.key]))throw Error('Utiliza enlaces que comiencen por https:// o http://.');}return data;}
function readLines(){return [...document.querySelectorAll('.line-row')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-line]')].map(el=>[el.dataset.line,el.type==='number'?Number(el.value):el.value])));}
function editor(kind,id=''){const schema=schemas[kind],old=id?get(state,id):null,date=today();let data=old||{date,hourly:state.settings.hourly,terms:state.settings.terms,lines:[{description:'',quantity:1,price:0}],materials:[]};if(!old&&kind==='quotes'&&Number(state.settings.validDays)>0){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+Number(state.settings.validDays));data.validUntil=d.toISOString().slice(0,10);}const hasLines=['quotes','invoices','orders','calculations'].includes(kind);return `<a class="back" href="#${kind}${id?'/'+id:''}">Volver a ${esc(schema.title.toLowerCase())}</a>`+head(old?'Editar '+schema.singular:'Crear '+schema.singular,kind==='accounts'?'No escribas contraseñas ni códigos de recuperación en este formulario.':kind==='resources'?'Los archivos permanecen privados. Compartirlos será una acción manual.':'')+`<form id="record-form" data-kind="${kind}" data-id="${id}" class="sheet"><div class="form-section form-grid">${schema.fields.filter(f=>!(old&&kind==='tasks'&&f.key==='status')).map(f=>field(f,data)).join('')}</div>${hasLines?`<section class="form-section"><h2>${kind==='calculations'?'Materiales del lote':'Conceptos'}</h2>${kind!=='calculations'?`<div class="toolbar"><select id="add-product" aria-label="Añadir desde el catálogo"><option value="">Añadir desde el catálogo…</option>${list(state,'products').map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div>`:''}<div class="lines" id="lines">${(kind==='calculations'?data.materials||[]:data.lines||[]).map(l=>lineRow(l,kind==='calculations')).join('')}</div><div class="section-space">${btn(kind==='calculations'?'Añadir material':'Añadir concepto','add-line',`data-material="${kind==='calculations'}"`)}</div><div id="calculation-result"></div></section>`:''}<div id="form-error" role="alert"></div><div class="form-actions"><a href="#${kind}${id?'/'+id:''}">Cancelar</a><button class="primary" type="submit">Guardar ${esc(schema.singular)}</button></div></form>`;}
function recalculate(){const form=$('#record-form');if(!form||!$('#calculation-result'))return;try{const data=readForm(form,schemas[form.dataset.kind].fields);if(form.dataset.kind==='calculations'){form.querySelector('[name=sale]').closest('label').hidden=data.mode==='margin';form.querySelector('[name=margin]').closest('label').hidden=data.mode!=='margin';data.materials=readLines();const c=calculate(data);$('#calculation-result').innerHTML=`<div class="result"><div><small>Costo total</small><strong>${money(c.cost)}</strong></div><div><small>Precio por unidad</small><strong>${money(c.unitSale)}</strong></div><div><small>Ganancia estimada</small><strong>${money(c.profit)}</strong></div><div><small>Margen sobre venta</small><strong>${c.margin.toFixed(2)} %</strong></div><div><small>Recargo sobre costo</small><strong>${c.markup.toFixed(2)} %</strong></div><div><small>Comisiones</small><strong>${money(c.commission)}</strong></div></div>${c.profit<0?'<p class="error">El precio no cubre los costos. Puedes guardarlo si así lo decides.</p>':''}`;}else{data.lines=readLines();const t=totals(data);$('#calculation-result').innerHTML=totalBlock(t);}}catch(e){$('#calculation-result').innerHTML=`<p class="error">${esc(e.message)}</p>`;}}
function totalBlock(t){return `<div class="doc-total"><div><span>Subtotal</span><span>${money(t.subtotal)}</span></div><div><span>Descuento</span><span>− ${money(t.discount)}</span></div><div><span>Envío</span><span>${money(t.shipping)}</span></div><div><span>Impuestos</span><span>${money(t.tax)}</span></div><div class="grand"><span>Total</span><span>${money(t.total)}</span></div>${t.advance?`<div><span>Anticipo solicitado</span><span>${money(t.advance)}</span></div>`:''}</div>`;}
function inlineForm(action,fields,extra='',label='Guardar'){return `<form class="inline-form" data-command="${action}" data-id="${recordId}">${fields.map(f=>field(f)).join('')}${extra}<div class="full"><button class="primary" type="submit">${label}</button></div><div class="inline-error full" role="alert"></div></form>`;}
const n=(key,label,extra={})=>({key,label,type:'number',...extra}),tx=(key,label)=>({key,label,type:'text'}),refField=(key,label,ref)=>({key,label,type:'ref',ref});
function detail(){const r=get(state,recordId),kind=r.kind,schema=schemas[kind],isDoc=['quotes','invoices','orders'].includes(kind);let actions='';
 if(!['quotes','invoices'].includes(kind)||r.status==='borrador')actions+=btn('Editar','edit');
 if(['quotes','calculations','products'].includes(kind))actions+=btn('Duplicar','duplicate');
 if(['quotes','invoices'].includes(kind)){actions+=btn('Descargar PDF','pdf');if(r.status==='borrador')actions+=btn(kind==='quotes'?'Marcar enviada':'Emitir factura','issue','',true);}
 if(kind==='quotes'){if(r.status==='enviada'){actions+=btn('Marcar aprobada','approve','',true)+btn('Rechazar','status','data-status="rechazada"');}actions+=btn('Nueva versión','revise');if(r.status==='aprobada')actions+=btn('Crear pedido','convert','data-kind="orders"')+btn('Crear factura','convert','data-kind="invoices"');}
 if(kind==='invoices'){if(r.status!=='anulada')actions+=btn('Anular','status','data-status="anulada"');else actions+=btn('Crear sustituta','replace');}
 if(kind==='purchases'&&!r.confirmed)actions+=btn('Confirmar entrada','purchase','',true);
 if(!['quotes','invoices','orders','purchases'].includes(kind))actions+=btn(r.archived?'Recuperar del archivo':'Archivar','archive');
 let body=`<a class="back" href="#${kind}">Volver a ${esc(schema.title.toLowerCase())}</a>`+head(r.number?`${r.number} · ${r.name}`:r.name,schemas[kind].title,actions)+badge(r.archived?'archivado':documentStatus(state,r));
 body+=`<section class="sheet sheet-pad section-space"><dl class="detail-grid">${schema.fields.filter(f=>!['file','checkbox'].includes(f.type)&&r[f.key]!==undefined&&r[f.key]!==''&&!(kind==='calculations'&&((r.mode==='margin'&&f.key==='sale')||(r.mode!=='margin'&&f.key==='margin')))).map(f=>`<div><dt>${esc(f.label)}</dt><dd>${f.type==='ref'&&state.records[r[f.key]]?link(state.records[r[f.key]].kind,state.records[r[f.key]]):f.type==='url'&&safeUrl(r[f.key])?`<a href="${esc(safeUrl(r[f.key]))}" target="_blank" rel="noopener noreferrer">Abrir enlace</a>`:esc(displayField(f,r[f.key]))}</dd></div>`).join('')}</dl></section>`;
 if(isDoc)body+=`<section class="sheet section-space"><div class="table-wrap"><table><thead><tr><th>Concepto</th><th>Cantidad</th><th>Precio</th><th>Importe</th></tr></thead><tbody>${r.lines.map(l=>`<tr><td>${esc(l.description)}</td><td>${l.quantity}</td><td class="num">${money(cents(l.price))}</td><td class="num">${money(Math.round(l.quantity*cents(l.price)))}</td></tr>`).join('')}</tbody></table></div>${totalBlock(totals(r))}</section>`;
 if(kind==='calculations'){const c=calculate(r);body+=`<section class="sheet sheet-pad section-space"><h2>Resultado del cálculo</h2><div class="result"><div><small>Costo del lote</small><strong>${money(c.cost)}</strong></div><div><small>Venta total</small><strong>${money(c.sale)}</strong></div><div><small>Ganancia estimada</small><strong>${money(c.profit)}</strong></div><div><small>Margen</small><strong>${c.margin.toFixed(2)} %</strong></div><div><small>Costo unitario</small><strong>${money(c.unitCost)}</strong></div><div><small>Precio unitario</small><strong>${money(c.unitSale)}</strong></div></div><p class="hint">Los importes guardados no cambian al actualizar materiales. Puedes editar este cálculo cuando quieras actualizarlo.</p>${(r.materials||[]).map(m=>`<p>${esc(m.description||state.records[m.materialId]?.name||'Material')}: ${m.quantity} × ${money(cents(m.unitCost))}</p>`).join('')}</section>`;}
 if(['invoices','purchases'].includes(kind))body+=paymentSection(r);
 if(kind==='materials'){body+=`<section class="sheet sheet-pad section-space"><h2>${r.track?'Existencias: '+stock(state,r.id)+' '+esc(r.unit||'unidades'):'Sin control de existencias'}</h2><p>Costo por unidad: ${money(cents(r.unitCost))}</p>${r.track?`<details><summary>Registrar entrada, uso o devolución</summary>${inlineForm('adjustStock',[n('quantity','Cantidad (negativa para descontar)',{min:-1000000}),tx('reason','Motivo'),refField('orderId','Pedido relacionado','orders')])}</details>${dataTable('movements',list(state,'movements',true).filter(m=>m.materialId===r.id).map(m=>({...m,name:`${m.name} · ${m.quantity}`,status:'registrado'}))).replaceAll('href="#movements/','href="#materials/')}`:''}</section>`;}
 if(['orders','tasks','content'].includes(kind)){const options=kind==='orders'?['pendiente','en diseño','esperando aprobación','en producción','listo para entregar','entregado','cancelado']:schemas[kind].fields.find(f=>f.key==='status').options;body+=`<section class="sheet sheet-pad section-space"><h2>Seguimiento</h2><div class="actions">${options.filter(s=>s!==r.status).map(s=>btn(s,'status',`data-status="${esc(s)}"`)).join('')}</div></section>`;}
 if(kind==='orders'){const calc=r.calculationId&&state.records[r.calculationId],est=r.estimate||(calc?calculate(calc):null),actual=(r.actualMaterials||0)+cents((r.actualHours||0)*(r.actualHourly||0))+(r.actualOther||0);body+=`<section class="sheet sheet-pad section-space"><h2>Materiales y costo real</h2><p>${r.actualComplete?'Costos marcados como completos':'Datos reales por completar; la ganancia sigue siendo estimada.'}</p><div class="result"><div><small>Costo estimado de referencia</small><strong>${est?money(est.cost):'Sin cálculo'}</strong></div><div><small>Costo real registrado</small><strong>${money(actual)}</strong></div><div><small>Ganancia según costos registrados</small><strong>${money(totals(r).total-totals(r).tax-actual-Math.round(totals(r).total*(est?.feePercent||0)/100))}</strong></div></div>${!r.consumed?`<details><summary>Confirmar consumo inicial</summary><p class="muted">Añade cada material utilizado. Las cantidades se descontarán una sola vez.</p><form id="consume-form" class="inline-form"><div id="consume-lines" class="full">${consumeRow()}</div><div class="full">${btn('Añadir material','consume-add')}<button type="submit" class="primary">Confirmar consumo</button></div><div class="inline-error full" role="alert"></div></form></details>`:'<p class="hint">Consumo inicial confirmado. Registra diferencias desde la ficha del material, indicando este pedido.</p>'}<details><summary>Registrar horas y otros costos reales</summary>${inlineForm('actual',[n('hours','Horas dedicadas',{value:r.actualHours||0}),n('hourly','Valor de tu hora RD$',{value:r.actualHourly||state.settings.hourly}),n('other','Otros costos reales RD$',{value:(r.actualOther||0)/100}),{key:'complete',label:'He completado todos los costos reales',type:'checkbox',value:r.actualComplete}])}</details></section>`;}
 if(kind==='resources'&&r.path)body+=`<section class="sheet sheet-pad section-space"><h2>Archivo privado</h2>${r.mime?.startsWith('image/')?`<img class="resource-preview" data-resource="${r.id}" alt="${esc(r.name)}">`:''}<p>${esc(r.fileName)} · ${Math.ceil(r.size/1024)} KB</p>${btn('Descargar archivo','download-file')}</section>`;
 body+=related(r);
 body+=`<section class="sheet sheet-pad section-space"><h2>Archivos y referencias</h2>${(r.resourceIds||[]).filter(id=>state.records[id]).map(id=>`<p>${link('resources',state.records[id])}</p>`).join('')||'<p class="muted">Sin recursos vinculados.</p>'}<details><summary>Vincular un recurso de la biblioteca</summary>${inlineForm('attach',[refField('resourceId','Recurso','resources')])}</details></section>`;
 return body;
}
function consumeRow(){return `<div class="consume-row form-grid">${field(refField('materialId','Material','materials'))}${field(n('quantity','Cantidad',{value:1,min:0.001}))}</div>`;}
function related(r){const rows=Object.values(state.records).filter(x=>x.id!==r.id&&!x.archived&&(x.clientId===r.id||x.quoteId===r.id||x.orderId===r.id||x.calculationId===r.id||x.campaignId===r.id||x.contentId===r.id||x.replacesId===r.id||(r.kind==='quotes'&&x.kind==='quotes'&&(x.rootId||x.id)===(r.rootId||r.id))));if(r.quoteId&&state.records[r.quoteId])rows.unshift(state.records[r.quoteId]);return rows.length?`<section class="sheet sheet-pad section-space"><h2>Historial y registros relacionados</h2>${rows.map(x=>`<div class="agenda-row"><div>${link(x.kind,x)}<small>${esc(schemas[x.kind]?.title)}</small></div>${badge(documentStatus(state,x))}</div>`).join('')}</section>`:'';}
function paymentSection(r){const payments=list(state,'payments',true).filter(p=>p.target===r.id);return `<section class="sheet sheet-pad section-space"><h2>Pagos y saldo</h2><p>Pagos netos: <strong>${money(paid(state,r.id))}</strong> · Saldo: <strong>${money(balance(state,r))}</strong></p>${payments.map(p=>`<div class="agenda-row"><div>${esc(p.name)}<small>${esc(p.date)} · ${esc(p.method)} · ${esc(p.reference)}${p.reason?' · '+esc(p.reason):''}</small></div><span class="num">${p.type==='refund'?'− ':''}${money(p.amount)}</span></div>`).join('')}${r.status!=='borrador'&&r.status!=='anulada'?`<details><summary>Registrar pago</summary>${inlineForm('payment',[n('amount','Importe RD$'),{key:'date',label:'Fecha',type:'date',value:today()},tx('method','Método de pago'),tx('reference','Referencia')],'','Registrar pago')}</details>`:''}${payments.some(p=>p.type!=='refund')?`<details><summary>Registrar reembolso o corrección</summary><p class="muted">Para corregir un pago, registra su devolución con el motivo y después añade el pago correcto.</p>${inlineForm('refund',[{key:'originalId',label:'Pago original',type:'select',options:payments.filter(p=>p.type!=='refund').map(p=>[p.id,`${p.date} · ${money(p.amount)}`])},n('amount','Importe a devolver RD$'),tx('reason','Motivo'),{key:'date',label:'Fecha',type:'date',value:today()},tx('method','Método'),tx('reference','Referencia')])}</details>`:''}</section>`;}
function finance(){return head('Finanzas','Cobros, pagos y saldos de tu negocio.',btn('Registrar gasto','new','data-kind="expenses"',true))+tabs()+`<div class="toolbar"><label>Desde<input type="date" id="finance-from" value="${today().slice(0,7)}-01"></label><label>Hasta<input type="date" id="finance-to" value="${today()}"></label><label>Cliente<select id="finance-client"><option value="">Todos</option>${list(state,'clients').map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Pedido<select id="finance-order"><option value="">Todos</option>${list(state,'orders').map(c=>`<option value="${c.id}">${esc(c.number)}</option>`).join('')}</select></label>${btn('Exportar movimientos','finance-csv')}</div><div id="finance-results"></div>`;}
function financeResults(){const f=cashflow(state,$('#finance-from').value,$('#finance-to').value,$('#finance-client').value,$('#finance-order').value);$('#finance-results').innerHTML=`<div class="overview"><div><small>Entradas del período</small><strong>${money(f.income)}</strong></div><div><small>Salidas del período</small><strong>${money(f.expense)}</strong></div><div><small>Diferencia</small><strong>${money(f.income-f.expense)}</strong></div><div><small>Por pagar · total</small><strong>${money(f.payable)}</strong></div></div><p class="hint">Estos importes reflejan dinero registrado. La ganancia por trabajo se consulta en la calculadora y en los pedidos.</p><section class="sheet"><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Concepto</th><th>Método</th><th>Importe</th></tr></thead><tbody>${f.entries.map(e=>`<tr><td>${esc(e.date)}</td><td>${e.target&&state.records[e.target]?link(state.records[e.target].kind,state.records[e.target]):esc(e.name)}</td><td>${esc(e.method)}</td><td class="num">${money(e.signed)}</td></tr>`).join('')||'<tr><td colspan="4">Sin movimientos en este período.</td></tr>'}</tbody></table></div></section><div class="two-col section-space"><section class="sheet sheet-pad"><h2>Cuentas por cobrar · todos los períodos</h2>${list(state,'invoices').filter(r=>!['borrador','anulada'].includes(r.status)&&balance(state,r)>0).map(r=>`<div class="agenda-row">${link('invoices',r)}<span>${money(balance(state,r))}</span></div>`).join('')||'<p class="muted">Sin saldos pendientes.</p>'}</section><section class="sheet sheet-pad"><h2>Cuentas por pagar · todos los períodos</h2>${list(state,'purchases').filter(r=>balance(state,r)>0).map(r=>`<div class="agenda-row">${link('purchases',r)}<span>${money(balance(state,r))}</span></div>`).join('')||'<p class="muted">Sin compras pendientes de pago.</p>'}</section></div>`;}
function calendar(){const selected=new Date(calendarDate+'T12:00:00Z'),first=new Date(selected);let count=1;if(calendarMode==='month'){first.setUTCDate(1);first.setUTCDate(first.getUTCDate()-(first.getUTCDay()+6)%7);count=42;}if(calendarMode==='week'){first.setUTCDate(first.getUTCDate()-(first.getUTCDay()+6)%7);count=7;}const all=events(state);let cells='';for(let i=0;i<count;i++){const d=new Date(first);d.setUTCDate(d.getUTCDate()+i);const key=d.toISOString().slice(0,10);cells+=`<div class="day ${key===today()?'today':''} ${d.getUTCMonth()!==selected.getUTCMonth()?'muted':''}"><span>${d.getUTCDate()}${calendarMode!=='month'?' '+new Intl.DateTimeFormat('es-DO',{month:'short',timeZone:'UTC'}).format(d):''}</span>${all.filter(e=>e.eventDate===key).map(e=>`<a class="event" href="#${e.kind}/${e.id}" style="display:block">${esc(e.time||'')} ${esc(e.name)}</a>`).join('')}</div>`;}
 return head('Calendario y tareas','Agenda interna · hora de República Dominicana',btn('Crear tarea','new','data-kind="tasks"',true))+tabs()+`<div class="toolbar">${btn('Anterior','calendar-prev')}${btn('Hoy','calendar-today')}${btn('Siguiente','calendar-next')}<input type="date" id="calendar-date" aria-label="Fecha del calendario" value="${calendarDate}"><select id="calendar-mode" aria-label="Vista del calendario">${[['month','Mes'],['week','Semana'],['day','Día']].map(([v,l])=>`<option value="${v}" ${calendarMode===v?'selected':''}>${l}</option>`).join('')}</select></div><h2>${new Intl.DateTimeFormat('es-DO',{month:'long',year:'numeric',timeZone:'UTC'}).format(selected)}</h2><div class="calendar ${calendarMode==='week'?'week':calendarMode==='day'?'day-view':''}">${calendarMode!=='day'?['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=>`<div class="weekday">${d}</div>`).join(''):''}${cells}</div>`;
}
function settings(){return head('Configuración','Tus datos habituales y el cuidado de tu información.')+tabs()+`<form id="settings-form" class="sheet"><div class="form-section form-grid">${settingsFields.map(f=>field(f,state.settings)).join('')}</div><div class="form-actions"><button type="submit" class="primary">Guardar configuración</button></div><div id="form-error" role="alert"></div></form><section class="sheet sheet-pad section-space"><h2>Exportación y recuperación</h2><p>Descarga una copia de tus registros y archivos. Contiene información privada de tu negocio: guárdala en un lugar protegido.</p><div class="actions">${btn('Descargar copia completa','backup','',true)}${btn('Exportar solo registros','backup-records')}${btn('Ver historial de cambios','history')}</div><div class="hint"><strong>Respaldo automático: pendiente de activación.</strong><br>Política acordada: diario, 30 días, registros y adjuntos. No hay una copia automática confirmada; requiere verificar costos y configurar el servicio.</div><details><summary>Recuperar registros desde una copia</summary><p>La recuperación añade registros que falten. Conserva los datos actuales y no sustituye facturas o pagos existentes. Para volver todo el panel a una fecha anterior hace falta una restauración administrativa.</p><form id="restore-form"><label>Archivo de copia<input type="file" name="backup" accept="application/json,.json" required></label><button type="submit">Revisar recuperación</button></form></details><div id="history-results"></div></section>`;}
function render(){objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];try{let body;if(route==='home')body=home();else if(route==='finance')body=finance();else if(route==='settings')body=settings();else if(route==='tasks'&&recordId==='calendar')body=calendar();else if(mode==='edit')body=editor(route,recordId);else if(recordId)body=detail();else body=listPage();shell(body);recalculate();if(route==='finance')financeResults();}catch(e){shell(head('No se pudo abrir esta pantalla')+`<p class="error">${esc(errorMessage(e))}</p><a href="#home">Volver al inicio</a>`);}}
async function hydrateImages(){for(const img of document.querySelectorAll('img[data-resource]')){const resource=state.records[img.dataset.resource];if(!resource?.path)continue;try{const blob=await store.downloadFile(resource.path);if(!img.isConnected)continue;const url=URL.createObjectURL(blob);objectUrls.push(url);img.src=url;}catch{if(!img.isConnected)continue;img.alt='Imagen no disponible';const message=document.createElement('p');message.className='image-error';message.textContent='No se pudo cargar la imagen. Pulsa Actualizar para volver a intentarlo.';message.setAttribute('role','status');img.after(message);}}}
async function execute(cmd){const result=await store.commit(cmd);state=result.state;return result;}
async function protect(fn,form=null){if(busy)return;busy=true;document.body.classList.add('busy');const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){const target=form?.querySelector('#form-error,.inline-error')||$('#login-error');if(target){target.className='error';target.textContent=errorMessage(e);}else notice(errorMessage(e),true);}finally{busy=false;document.body.classList.remove('busy');buttons.forEach(b=>b.disabled=false);}}
function csv(rows){const keys=[...new Set(rows.flatMap(Object.keys))];const cell=v=>{let text=typeof v==='object'?JSON.stringify(v):String(v??'');if(/^[=+\-@\t\r]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';};return new Blob(['\ufeff'+[keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n')],{type:'text/csv;charset=utf-8'});}
document.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;
 if(action==='menu'||action==='menu-close'){const open=action==='menu';$('#sidebar').classList.toggle('open',open);$('.menu-toggle')?.setAttribute('aria-expanded',String(open));(open?$('#sidebar .mobile-close'):$('.menu-toggle'))?.focus();return;}
 if(action==='notes'){const dialog=$('#quick-notes-dialog');dialog?.showModal();dialog?.querySelector('textarea')?.focus();return;}
 if(action==='notes-close'){$('#quick-notes-dialog')?.close();return;}
 if(action==='new'){location.hash=`${button.dataset.kind}/new`;return;}if(action==='edit'){location.hash=`${route}/${recordId}/edit`;return;}
 if(action==='remove-line'){button.closest('.line-row').remove();recalculate();return;}
 if(action==='add-line'){$('#lines').insertAdjacentHTML('beforeend',lineRow({},button.dataset.material==='true'));recalculate();return;}
 if(action==='consume-add'){$('#consume-lines').insertAdjacentHTML('beforeend',consumeRow());return;}
 if(action==='toggle-board'){listMode=listMode==='board'?'list':'board';render();return;}if(action==='calendar'){location.hash='tasks/calendar';return;}
 if(action.startsWith('calendar-')){let d=new Date(calendarDate+'T12:00:00Z');if(action==='calendar-today')calendarDate=today();else{const direction=action==='calendar-next'?1:-1;if(calendarMode==='month'){d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+direction);}else d.setUTCDate(d.getUTCDate()+direction*(calendarMode==='week'?7:1));calendarDate=d.toISOString().slice(0,10);}render();return;}
 protect(async()=>{
  if(action==='logout'){await store.logout();return;}
  if(action==='delete-note'){const note=get(state,button.dataset.id);if(note.kind!=='resources'||note.recordType!=='quick-note')throw Error('No se encontró esta nota.');if(!await ask('¿Eliminar esta nota?'))return;await execute({action:'archive',id:note.id});render();$('#quick-notes-dialog')?.showModal();notice('Nota eliminada.');return;}
  if(action==='reset'){const email=$('#login-form [name=email]').value;if(!email)throw Error('Escribe tu correo para recuperar el acceso.');await store.resetPassword(email);notice('Si el correo corresponde a una cuenta, recibirás instrucciones para recuperar el acceso.');return;}
  if(action==='refresh'){state=await store.load();render();notice('Información actualizada.');return;}
  if(action==='csv'){download(csv(filtered()),`${route}-${today()}.csv`);return;}
  if(action==='finance-csv'){download(csv(cashflow(state,$('#finance-from').value,$('#finance-to').value,$('#finance-client').value,$('#finance-order').value).entries),`movimientos-${today()}.csv`);return;}
  if(action==='pdf'){const r=get(state,recordId),doc={...r,issuer:r.issuer||state.settings,client:r.client||state.records[r.clientId]};let logo=null;const logoPath=doc.issuer.logoPath||(!r.issuedAt?state.records[doc.issuer.logoResourceId]?.path:null);if(logoPath){const blob=await store.downloadFile(logoPath);if(!blob.type.startsWith('image/'))throw Error('Selecciona una imagen como logotipo en Configuración.');const image=await createImageBitmap(blob),canvas=document.createElement('canvas');canvas.width=400;canvas.height=Math.max(1,Math.round(400*image.height/image.width));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);image.close();const jpeg=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));logo={bytes:new Uint8Array(await jpeg.arrayBuffer()),width:canvas.width,height:canvas.height};}download(documentPdf(doc,{paid:paid(state,r.id),logo}),`${r.number}${r.revision>1?'-v'+r.revision:''}.pdf`);return;}
  if(action==='download-file'){const r=get(state,recordId);download(await store.downloadFile(r.path),r.fileName);return;}
  if(action==='backup'||action==='backup-records'){notice('Preparando la copia. Mantén esta ventana abierta.');const backup=await store.exportBackup(action==='backup');download(new Blob([JSON.stringify(backup)],{type:'application/json'}),`Life-Deco-Art-copia-${today()}.json`);notice('Copia preparada para descargar.');return;}
  if(action==='history'){const logs=await store.history();$('#history-results').innerHTML='<h3 class="section-space">Historial de cambios</h3>'+logs.slice(0,100).map(h=>`<p><small>${esc(h.at)}</small> · ${esc(h.action)} · ${esc(state.records[h.target]?.number||state.records[h.target]?.name||'Configuración')}</p>`).join('');return;}
  const cmd={action,id:recordId};if(action==='convert')cmd.kind=button.dataset.kind;
  if(action==='status'){cmd.status=button.dataset.status;if(['anulada','cancelado'].includes(cmd.status)){const reason=await ask('Indica el motivo. Los documentos, pagos y materiales conservarán su historial.',true);if(reason===null)return;cmd.reason=reason;}}
  if(['issue','purchase','approve','replace'].includes(action)&&!await ask(({issue:'¿Confirmas emitir este documento? Sus importes se conservarán.',purchase:'¿Confirmas recibir esta compra y actualizar las existencias?',approve:'¿Confirmas que el cliente aprobó esta cotización?',replace:'¿Crear una nueva factura vinculada a la anulada? Los pagos permanecerán en su documento original.'})[action]))return;
  const result=await execute(cmd);if(['convert','duplicate','revise','replace'].includes(action)&&result.result){const r=state.records[result.result];location.hash=`${r.kind}/${r.id}${['revise','replace','duplicate'].includes(action)?'/edit':''}`;}else render();notice('Cambio guardado.');
 });
});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;$('#list-results').innerHTML=listResults();hydrateImages();}if(e.target.closest('#record-form'))recalculate();});
document.addEventListener('change',e=>{if(e.target.id==='filter'){filter=e.target.value;$('#list-results').innerHTML=listResults();hydrateImages();}if(e.target.id==='calendar-mode'){calendarMode=e.target.value;render();}if(e.target.id==='calendar-date'&&e.target.value){calendarDate=e.target.value;render();}if(e.target.id.startsWith('finance-'))financeResults();if(e.target.dataset.line==='materialId'){const m=state.records[e.target.value],row=e.target.closest('.line-row');if(m){row.querySelector('[data-line=unitCost]').value=m.unitCost||0;row.querySelector('[data-line=description]').value=m.name;}recalculate();}if(e.target.id==='add-product'&&e.target.value){const p=get(state,e.target.value);$('#lines').insertAdjacentHTML('beforeend',lineRow({description:p.name,quantity:1,price:p.price||0}));e.target.value='';recalculate();}if(e.target.closest('#record-form'))recalculate();});
document.addEventListener('submit',event=>{event.preventDefault();const form=event.target;protect(async()=>{
 if(form.id==='login-form'){const fd=new FormData(form);await store.login(String(fd.get('email')),String(fd.get('password')));return;}
 if(form.id==='quick-note-form'){const note=String(new FormData(form).get('note')||'').trim();if(!note)throw Error('Escribe la nota antes de guardarla.');const name=note.split(/\r?\n/).find(line=>line.trim())?.trim()||'Nota';await execute({action:'save',kind:'resources',data:{name:name.slice(0,80),note,recordType:'quick-note',status:'activo'}});render();$('#quick-notes-dialog')?.showModal();notice('Nota guardada.');return;}
 if(form.id==='record-form'){
  const kind=form.dataset.kind,data=readForm(form,schemas[kind].fields);if(['quotes','invoices','orders'].includes(kind))data.lines=readLines();if(kind==='calculations')data.materials=readLines();if(kind==='tasks'&&form.dataset.id)data.status=state.records[form.dataset.id].status;
  if(kind==='resources'){const file=form.querySelector('[type=file]').files[0];if(file)Object.assign(data,await store.upload(file));}
  const result=await execute({action:'save',kind,id:form.dataset.id||undefined,data});location.hash=`${kind}/${result.result}`;notice('Registro guardado.');return;
 }
 if(form.id==='settings-form'){await execute({action:'settings',data:readForm(form,settingsFields)});render();notice('Configuración guardada.');return;}
 if(form.id==='restore-form'){const file=form.querySelector('input').files[0];if(file.size>150*1024*1024)throw Error('La copia necesita una restauración administrativa por su tamaño.');const backup=JSON.parse(await file.text());if(!await ask('¿Recuperar los registros que falten de esta copia? Se conservarán los registros actuales.'))return;const result=await store.restoreBackup(backup);state=result.state;render();notice(`${result.count} registros recuperados.`);return;}
 if(form.id==='consume-form'){const lines=[...form.querySelectorAll('.consume-row')].map(row=>({materialId:row.querySelector('[name=materialId]').value,quantity:Number(row.querySelector('[name=quantity]').value)}));await execute({action:'consume',id:recordId,lines});render();notice('Consumo confirmado.');return;}
 if(form.dataset.command){const fd=new FormData(form),data=Object.fromEntries(fd),action=form.dataset.command;let cmd={...data,action,id:recordId};if(action==='payment'||action==='refund')cmd={...cmd,action:'payment',target:recordId,type:action==='refund'?'refund':'payment'};if(action==='adjustStock')cmd.materialId=recordId;if(action==='actual')cmd.complete=fd.has('complete');await execute(cmd);render();notice('Cambio guardado.');}
 },form);});
window.addEventListener('hashchange',()=>{if(user){parseRoute();render();$('#main')?.focus({preventScroll:true});}});
window.addEventListener('keydown',e=>{const menu=$('#sidebar.open');if(!menu)return;if(e.key==='Escape'){menu.classList.remove('open');$('.menu-toggle')?.setAttribute('aria-expanded','false');$('.menu-toggle')?.focus();}if(e.key==='Tab'){const controls=[...menu.querySelectorAll('a,button')].filter(el=>!el.disabled&&el.getClientRects().length),first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('offline',()=>notice('Sin conexión. Espera a recuperar internet antes de guardar.',true));
window.addEventListener('online',()=>notice('Conexión recuperada. Actualiza antes de continuar.'));
try{store=await import('./store.mjs');store.observeAuth(async u=>{user=u;if(!u){state=emptyState();loginScreen();return;}shell(head('Abriendo tu espacio…','Comprobando acceso privado y cargando registros.'));try{const loaded=await store.load();if(user!==u)return;state=loaded;parseRoute();render();}catch(e){if(user!==u)return;shell(head('Acceso privado pendiente')+`<p class="error">${esc(errorMessage(e))}</p><p>La sesión está iniciada, pero todavía no se pueden abrir los registros privados. Reintenta después de habilitar el acceso.</p>${btn('Volver a comprobar','refresh')}`);}});}catch(e){loginScreen('No se pudo conectar con el servicio de acceso. Comprueba tu conexión y recarga la página.');}
