// Labels are intentionally editable in a later naming pass.
const f=(key,label,type='text',extra={})=>({key,label,type,...extra});
const notes=f('notes','Notas','textarea'),date=f('date','Fecha','date'),client=f('clientId','Cliente','ref',{ref:'clients'}),order=f('orderId','Pedido relacionado','ref',{ref:'orders'});
export const schemas={
 clients:{title:'Clientes',singular:'cliente',description:'Organiza la información, pedidos e historial de cada cliente.',fields:[f('name','Nombre','text',{required:true}),f('clientType','Tipo de cliente','select',{options:[['person','Persona'],['company','Empresa']]}),f('companyName','Nombre de la empresa'),f('contactName','Persona de contacto'),f('role','Cargo'),f('phone','Teléfono o WhatsApp'),f('email','Correo electrónico','email'),f('instagram','Instagram'),f('rnc','RNC'),f('source','Cómo conoció Life Deco Art'),f('preferredChannel','Canal preferido','select',{options:['','WhatsApp','Llamada','Correo','Instagram']}),f('interests','Intereses'),f('tags','Etiquetas'),f('observations','Observaciones','textarea'),f('identityNumber','Cédula o RNC'),f('address','Dirección'),f('sector','Sector'),f('city','Ciudad o provincia'),f('deliveryReference','Referencia para la entrega','textarea'),f('deliveryPreference','Preferencia de entrega','select',{options:['','Recoger','Entrega local','Envío']}),notes]},
 products:{title:'Productos y servicios',singular:'producto o servicio',description:'Crea tu oferta y conoce el costo detrás de cada precio.',fields:[f('name','Nombre','text',{required:true}),f('itemType','Tipo','select',{options:[['producto','Producto'],['servicio','Servicio']]}),f('category','Categoría'),f('code','Código interno'),f('description','Descripción','textarea'),f('production','Forma de producción'),f('lead','Tiempo habitual de elaboración'),f('variants','Variantes'),f('finishedStock','Controlar unidades terminadas','checkbox'),f('modality','Modalidad'),f('duration','Duración estimada'),f('includes','Qué incluye'),f('conditions','Condiciones','textarea'),f('price','Precio de venta RD$','number'),notes]},
 calculations:{title:'Calculadora',singular:'cálculo',description:'Conoce tus costos antes de decidir cuánto cobrar.',fields:[f('name','Nombre del cálculo','text',{required:true}),f('units','Unidades producidas','number',{value:1,min:1}),f('hours','Horas de trabajo','number'),f('hourly','Valor de tu hora RD$','number'),f('packaging','Empaque del lote RD$','number'),f('other','Otros costos del lote RD$','number'),f('feePercent','Comisión sobre la venta %','number'),f('mode','Calcular a partir de','select',{options:[['price','precio de venta'],['margin','margen deseado']]}),f('sale','Precio por unidad RD$','number'),f('margin','Margen deseado %','number'),notes]},
 quotes:{title:'Cotizaciones',singular:'cotización',description:'Prepara propuestas y conserva lo acordado.',fields:[f('name','Nombre del trabajo','text',{required:true}),client,date,f('validUntil','Válida hasta','date'),f('due','Entrega prevista','date'),f('calculationId','Cálculo de referencia','ref',{ref:'calculations'}),f('discountType','Tipo de descuento','select',{options:[['amount','monto RD$'],['percent','porcentaje']]}),f('discount','Descuento','number'),f('shipping','Envío RD$','number'),f('taxPercent','Impuesto % (opcional)','number'),f('advanceType','Tipo de anticipo','select',{options:[['amount','monto RD$'],['percent','porcentaje']]}),f('advance','Anticipo solicitado','number'),f('terms','Condiciones','textarea'),notes]},
 invoices:{title:'Facturas',singular:'factura',description:'Documentos de cobro sin comprobante fiscal.',fields:[]},
 orders:{title:'Pedidos y proyectos',singular:'pedido',description:'Del primer diseño a la entrega.',fields:[]},
 materials:{title:'Materiales e inventario',singular:'material',description:'Qué utilizas, cuánto cuesta y cuánto queda.',fields:[f('name','Material','text',{required:true}),f('category','Categoría'),f('presentation','Presentación de compra'),f('unit','Unidad de consumo'),f('packageUnits','Rendimiento por unidad comprada','number',{value:1,min:0.001}),f('packageCost','Costo de la presentación RD$','number'),f('supplierId','Proveedor habitual','ref',{ref:'suppliers'}),f('sourceUrl','Enlace de consulta','url'),f('track','Controlar existencias','checkbox'),f('minimum','Mínimo para reposición','number'),notes]},
 suppliers:{title:'Proveedores y compras',singular:'proveedor',description:'Dónde compras y cuánto pagaste cada vez.',fields:[f('name','Nombre','text',{required:true}),f('contact','Teléfono o WhatsApp'),f('email','Correo','email'),f('url','Enlace principal de consulta','url'),notes]},
 purchases:{title:'Compras',singular:'compra',description:'Registra cada compra y actualiza el inventario cuando la recibas.',fields:[f('name','Descripción','text',{required:true}),f('supplierId','Proveedor','ref',{ref:'suppliers'}),date,f('reference','Referencia o factura'),f('shipping','Envío de la compra RD$','number'),f('other','Otros cargos RD$','number'),f('total','Costo total RD$','number'),notes]},
 expenses:{title:'Gastos',singular:'gasto',description:'Gastos pagados que no hayas registrado como compra.',fields:[f('name','Concepto','text',{required:true}),f('amount','Importe pagado RD$','number'),f('category','Categoría'),date,f('method','Método de pago'),f('reference','Referencia'),client,order,notes]},
 campaigns:{title:'Campañas',singular:'campaña',description:'Agrupa contenido para un lanzamiento o temporada.',fields:[f('name','Nombre','text',{required:true}),f('start','Inicio','date'),f('end','Fin','date'),f('objective','Objetivo','textarea'),notes]},
 content:{title:'Contenido',singular:'contenido',description:'De una idea a una publicación. El envío a redes es manual.',fields:[f('name','Título de la idea','text',{required:true}),f('channel','Canal'),f('format','Formato'),f('campaignId','Campaña','ref',{ref:'campaigns'}),f('status','Estado','select',{options:['idea','en preparación','listo','programado','publicado']}),date,f('copy','Texto de la publicación','textarea'),f('url','Enlace de referencia','url'),notes]},
 resources:{title:'Recursos de marca',singular:'recurso',description:'Diseños, referencias y archivos que puedes volver a utilizar.',fields:[f('name','Nombre','text',{required:true}),f('category','Categoría'),f('tags','Etiquetas (separadas por comas)'),f('role','Uso','select',{options:['referencia','propuesta','diseño final','logotipo','fotografía','video','plantilla','documento','colores y tipografías']}),f('visibility','Destino','select',{options:['interno','para compartir manualmente']}),f('url','Enlace externo (opcional)','url'),f('file','Archivo (máximo 15 MB)','file'),notes]},
 accounts:{title:'Servicios',singular:'servicio',description:'Tus plataformas, planes, costos y próximas renovaciones.',fields:[f('name','Servicio','text',{required:true}),f('category','Categoría'),f('status','Estado','select',{value:'activo',options:['activo','prueba','pausado','cancelado']}),f('url','Enlace de acceso','url'),f('username','Correo o usuario'),f('managerUrl','Enlace al gestor de contraseñas','url'),f('subscription','Plan o suscripción'),f('billing','Frecuencia de pago','select',{options:[['gratis','gratuito'],['mensual','mensual'],['anual','anual'],['otro','otro']]}),f('cost','Costo de renovación RD$','number'),f('autoRenew','Renovación automática','checkbox'),f('renewal','Próxima renovación','date'),f('reminderDays','Avisar con cuántos días de anticipación','number'),f('responsible','Responsable o correo de gestión'),notes]},
 tasks:{title:'Calendario y tareas',singular:'tarea',description:'Tus pendientes del negocio y personales relacionados.',fields:[f('name','Tarea','text',{required:true}),f('description','Descripción','textarea'),date,f('time','Hora (opcional)','time'),f('priority','Prioridad','select',{options:['normal','alta','baja']}),f('status','Estado','select',{options:['pendiente','en curso','completada','cancelada']}),f('scope','Ámbito','select',{options:['negocio','personal relacionado']}),f('repeat','Repetir','select',{options:['ninguna','diaria','semanal','mensual']}),client,order,f('contentId','Contenido relacionado','ref',{ref:'content'})]}
};
schemas.invoices.fields=schemas.quotes.fields.filter(f=>!['validUntil','calculationId'].includes(f.key)).map(f=>f.key==='due'?{...f,label:'Vencimiento del saldo'}:f);
schemas.orders.fields=schemas.quotes.fields.filter(f=>!['validUntil'].includes(f.key));
export const settingsFields=[f('name','Nombre comercial','text',{required:true}),f('email','Correo comercial','email'),f('phone','Teléfono'),f('address','Dirección (opcional)'),f('logoResourceId','Logotipo PNG/JPG','ref',{ref:'resources'}),f('hourly','Valor habitual de tu hora RD$','number'),f('validDays','Días habituales de vigencia de una cotización (0 = elegir cada vez)','number'),f('terms','Condiciones habituales de cotización','textarea'),f('paymentInstructions','Instrucciones habituales de pago','textarea')];
