// Labels are intentionally editable in a later naming pass.
const f=(key,label,type='text',extra={})=>({key,label,type,...extra});
const notes=f('notes','Notas','textarea'),date=f('date','Fecha','date'),client=f('clientId','Cliente','ref',{ref:'clients'}),order=f('orderId','Pedido relacionado','ref',{ref:'orders'});
export const schemas={
 clients:{title:'Clientes',singular:'cliente',description:'Cada conversación, propuesta y trabajo en un mismo lugar.',fields:[f('name','Nombre','text',{required:true}),f('company','Empresa'),f('phone','Teléfono / WhatsApp'),f('email','Correo','email'),f('social','Redes sociales'),f('source','Cómo llegó a tu marca'),f('preferences','Preferencias','textarea'),notes]},
 products:{title:'Productos y servicios',singular:'producto o servicio',description:'Tu catálogo interno para preparar nuevos trabajos.',fields:[f('name','Nombre','text',{required:true}),f('type','Tipo','select',{options:['físico','digital','servicio']}),f('category','Categoría'),f('description','Descripción','textarea'),f('variants','Tamaños, materiales y acabados','textarea'),f('pricing','Precio','select',{options:['fijo','por cotizar']}),f('price','Precio de venta RD$','number'),f('calculationId','Cálculo asociado','ref',{ref:'calculations'}),notes]},
 calculations:{title:'Calculadora',singular:'cálculo',description:'Conoce tus costos antes de decidir cuánto cobrar.',fields:[f('name','Nombre del cálculo','text',{required:true}),f('units','Unidades producidas','number',{value:1,min:1}),f('hours','Horas de trabajo','number'),f('hourly','Valor de tu hora RD$','number'),f('packaging','Empaque del lote RD$','number'),f('other','Otros costos del lote RD$','number'),f('feePercent','Comisión sobre la venta %','number'),f('mode','Calcular a partir de','select',{options:[['price','precio de venta'],['margin','margen deseado']]}),f('sale','Precio por unidad RD$','number'),f('margin','Margen deseado %','number'),notes]},
 quotes:{title:'Cotizaciones',singular:'cotización',description:'Prepara propuestas y conserva lo acordado.',fields:[f('name','Nombre del trabajo','text',{required:true}),client,date,f('validUntil','Válida hasta','date'),f('due','Entrega prevista','date'),f('calculationId','Cálculo de referencia','ref',{ref:'calculations'}),f('discountType','Tipo de descuento','select',{options:[['amount','monto RD$'],['percent','porcentaje']]}),f('discount','Descuento','number'),f('shipping','Envío RD$','number'),f('taxPercent','Impuesto % (opcional)','number'),f('advanceType','Tipo de anticipo','select',{options:[['amount','monto RD$'],['percent','porcentaje']]}),f('advance','Anticipo solicitado','number'),f('terms','Condiciones','textarea'),notes]},
 invoices:{title:'Facturas',singular:'factura',description:'Documentos de cobro sin comprobante fiscal.',fields:[]},
 orders:{title:'Pedidos y proyectos',singular:'pedido',description:'Del primer diseño a la entrega.',fields:[]},
 materials:{title:'Materiales e inventario',singular:'material',description:'Costos actualizados y existencias cuando las necesites.',fields:[f('name','Material','text',{required:true}),f('category','Categoría'),f('unit','Unidad de uso (hoja, metro, pieza…)'),f('packageUnits','Unidades por paquete','number',{value:1,min:0.001}),f('packageCost','Costo del paquete RD$','number'),f('supplier','Proveedor'),f('track','Controlar existencias','checkbox'),f('minimum','Avisar al llegar a esta cantidad','number'),notes]},
 purchases:{title:'Compras',singular:'compra',description:'Registra la compra, confirma su entrada y añade sus pagos.',fields:[f('name','Descripción','text',{required:true}),f('materialId','Material','ref',{ref:'materials'}),f('quantity','Unidades compradas','number',{min:0.001}),f('total','Costo total RD$','number'),f('supplier','Proveedor'),date,notes]},
 expenses:{title:'Gastos',singular:'gasto',description:'Gastos pagados que no hayas registrado como compra.',fields:[f('name','Concepto','text',{required:true}),f('amount','Importe pagado RD$','number'),f('category','Categoría'),date,f('method','Método de pago'),f('reference','Referencia'),client,order,notes]},
 campaigns:{title:'Campañas',singular:'campaña',description:'Agrupa contenido para un lanzamiento o temporada.',fields:[f('name','Nombre','text',{required:true}),f('start','Inicio','date'),f('end','Fin','date'),f('objective','Objetivo','textarea'),notes]},
 content:{title:'Contenido',singular:'contenido',description:'De una idea a una publicación. El envío a redes es manual.',fields:[f('name','Título de la idea','text',{required:true}),f('channel','Canal'),f('format','Formato'),f('campaignId','Campaña','ref',{ref:'campaigns'}),f('status','Estado','select',{options:['idea','en preparación','listo','programado','publicado']}),date,f('copy','Texto de la publicación','textarea'),f('url','Enlace de referencia','url'),notes]},
 resources:{title:'Recursos de marca',singular:'recurso',description:'Diseños, referencias y archivos que puedes volver a utilizar.',fields:[f('name','Nombre','text',{required:true}),f('category','Categoría'),f('tags','Etiquetas (separadas por comas)'),f('role','Uso','select',{options:['referencia','propuesta','diseño final','logotipo','fotografía','video','plantilla','documento','colores y tipografías']}),f('visibility','Destino','select',{options:['interno','para compartir manualmente']}),f('url','Enlace externo (opcional)','url'),f('file','Archivo (máximo 15 MB)','file'),notes]},
 accounts:{title:'Accesos y cuentas',singular:'cuenta',description:'Encuentra tus servicios y sus próximas renovaciones.',fields:[f('name','Servicio','text',{required:true}),f('url','Enlace de acceso','url'),f('username','Correo o usuario'),f('category','Categoría'),f('managerUrl','Enlace al gestor de contraseñas','url'),f('subscription','Suscripción'),f('cost','Costo de renovación RD$','number'),f('renewal','Próxima renovación','date'),notes]},
 tasks:{title:'Calendario y tareas',singular:'tarea',description:'Tus pendientes del negocio y personales relacionados.',fields:[f('name','Tarea','text',{required:true}),f('description','Descripción','textarea'),date,f('time','Hora (opcional)','time'),f('priority','Prioridad','select',{options:['normal','alta','baja']}),f('status','Estado','select',{options:['pendiente','en curso','completada','cancelada']}),f('scope','Ámbito','select',{options:['negocio','personal relacionado']}),f('repeat','Repetir','select',{options:['ninguna','diaria','semanal','mensual']}),client,order,f('contentId','Contenido relacionado','ref',{ref:'content'})]}
};
schemas.invoices.fields=schemas.quotes.fields.filter(f=>!['validUntil','calculationId'].includes(f.key)).map(f=>f.key==='due'?{...f,label:'Vencimiento del saldo'}:f);
schemas.orders.fields=schemas.quotes.fields.filter(f=>!['validUntil'].includes(f.key));
export const settingsFields=[f('name','Nombre comercial','text',{required:true}),f('email','Correo comercial','email'),f('phone','Teléfono'),f('address','Dirección (opcional)'),f('logoResourceId','Logotipo PNG/JPG','ref',{ref:'resources'}),f('hourly','Valor habitual de tu hora RD$','number'),f('validDays','Días habituales de vigencia (0 = elegir cada vez)','number'),f('terms','Condiciones habituales','textarea'),f('paymentInstructions','Instrucciones de pago','textarea')];
